apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: lhab4geb6-nodejs
  janus-idp.io/tekton: lhab4geb6-nodejs
  backstage.io/kubernetes-id: lhab4geb6-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: lhab4geb6-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
